name: finanzas_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # ✅ ACTUALIZADO para Flutter moderno

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies - VERSIONES ACTUALIZADAS
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  
  # Otras dependencias actualizadas
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/  # ✅ COMENTADO temporalmente