name: finanzas_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'  # ✅ COMPATIBLE con Dart 3.2.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies COMPATIBLES
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  
  # Otras dependencias COMPATIBLES
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  intl: ^0.18.1  # ✅ COMPATIBLE con Dart 3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # ✅ COMPATIBLE con Dart 3.2.0

flutter:
  uses-material-design: true
