name: Build APK Simple
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build apk --debug
      - name: Show APK Path
        run: echo "APK ready at: build/app/outputs/flutter-apk/app-debug.apk"
