name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: cd finanzas_app && flutter pub get
      - run: cd finanzas_app && flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: finanzas-app
          path: finanzas_app/build/app/outputs/flutter-apk/app-debug.apk
