name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          
      - name: Navigate to app directory
        run: cd finanzas_app
          
      - name: Install dependencies
        run: |
          cd finanzas_app
          flutter pub get
        
      - name: Build APK
        run: |
          cd finanzas_app
          flutter build apk --debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: finanzas_app/build/app/outputs/flutter-apk/app-debug.apk
